runtime: python-3.11

services:
  - type: web
    name: confirmit-fastapi
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir --prefer-binary -r requirements.txt
    startCommand: |
      uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PORT
        value: "10000"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONWARNINGS
        value: "ignore"
      - key: TZ
        value: "UTC"
